/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2025-02-12 15:45:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/SAMSUNG/JavaPro/66.Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Movie_Project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1723603073652L));
    _jspx_dependants.put("jar:file:/C:/Users/SAMSUNG/JavaPro/66.Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Movie_Project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt-1_0-rt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html;\" charset=\"utf-8\">\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-2.2.4.min.js\" integrity=\"sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script defer type=\"text/javascript\" src=\"/resources/JS/user.js\" charset=\"euc-kr\"></script>\r\n");
      out.write("<link rel= \"stylesheet\" href =\"/resources/CSS/userform.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\">\r\n");
      out.write("\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("      <h1>회원가입</h1>     \r\n");
      out.write("      \r\n");
      out.write("            <form action=\"/user/join\" name=\"userform\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("         <!-- 사용자 입력 폼 -->\r\n");
      out.write("         <div class=\"formdiv\">\r\n");
      out.write("            <span id=\"icon\" class=\"material-symbols-outlined\">person</span>\r\n");
      out.write("            <input type=\"text\" name=\"uid\" id=\"uid\" placeholder=\"아이디를 입력해주세요\">\r\n");
      out.write("            <input type=\"hidden\" name=\"dupl\" id=\"dupl\" value=0 /> \r\n");
      out.write("            <button type=\"button\" class=\"btn1\" id=\"duplidbtn\" onclick=\"duplidchk();\">아이디 중복 체크</button>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"formdiv\">\r\n");
      out.write("            <span class=\"material-symbols-outlined\">vpn_key</span>\r\n");
      out.write("            <input type=\"password\" name=\"upw\" id=\"upw\" placeholder=\"비밀번호를 입력해주세요\">\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"formdiv\">\r\n");
      out.write("            <span class=\"material-symbols-outlined\">person_add</span>\r\n");
      out.write("            <input type=\"text\" name=\"uname\" id=\"uname\" placeholder=\"이름을 입력해주세요\">\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"formdiv\">\r\n");
      out.write("            <span class=\"material-symbols-outlined\">email</span>\r\n");
      out.write("            <input type=\"text\" name=\"umail\" id=\"umail\" placeholder=\"이메일을 입력해주세요\">\r\n");
      out.write("            <button class=\"btn1\" id=\"emailCheckButton\" onclick=\"javascript:sendmail();\">이메일 확인</button>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"emailchk\">   \r\n");
      out.write("          <span class=\"material-symbols-outlined\">mark_email_read</span>\r\n");
      out.write("          <input type=\"text\" name=\"umailChk\" id=\"umailChk\" placeholder=\"인증번호를 입력해주세요\">\r\n");
      out.write("          <input type=\"hidden\" name=\"mailChk\" id=\"mailChk\" value=0/>\r\n");
      out.write("          <button class=\"btn1\" type=\"button\" onclick=\"verifycode();\">확인</button>\r\n");
      out.write("       </div>\r\n");
      out.write("         <div class=\"formdiv\">\r\n");
      out.write("            <span class=\"material-symbols-outlined\">phone_iphone</span>\r\n");
      out.write("            <input class=\"phone\" type=\"tel\" name=\"uphone1\" id=\"uphone1\" value=\"010\" readonly >-\r\n");
      out.write("               <input class=\"phone\" type=\"tel\" name=\"uphone2\" id=\"uphone2\" placeholder=\"1234\" maxlength = \"4\" >-\r\n");
      out.write("              <input class=\"phone\" type=\"tel\" name=\"uphone3\" id=\"uphone3\" placeholder=\"5678\" maxlength = \"4\"><br>\r\n");
      out.write("               <input type=\"hidden\" name=\"uphone\" id=\"uphone\">\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"formdiv\">\r\n");
      out.write("            <span class=\"material-symbols-outlined\">calendar_month</span>\r\n");
      out.write("            <input class=\"date\" type=\"date\" name=\"frontbirth\" id=\"frontbirth\" placeholder=\"생년월일 6자리를 입력해주세요\">\r\n");
      out.write("                  <input type=\"hidden\" name=\"ubirth\" id=\"ubirth\">\r\n");
      out.write("               <input type=\"radio\" name=\"ugender\" value=\"M\">남\r\n");
      out.write("               <input type=\"radio\" name=\"ugender\" value=\"F\">여<br>\r\n");
      out.write("            </div>\r\n");
      out.write("      <div class=\"formdiv\">\r\n");
      out.write("            <span class=\"material-symbols-outlined\">account_box</span>\r\n");
      out.write("            <input type=\"text\" name=\"jspsaveprofile\" id=\"jspsaveprofile\" value=\"프로필사진\" readonly>\r\n");
      out.write("            <input type=\"file\" name=\"jspprofile\" id=\"jspprofile\" onchange=\"changeprofile()\"/><br>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"formdiv\">\r\n");
      out.write("            <span class=\"material-symbols-outlined\">home</span>\r\n");
      out.write("            <input type=\"text\" name=\"upost\" id=\"upost\" readonly placeholder=\"우편번호\">\r\n");
      out.write("            <input class=\"btn1\" type=\"button\" id=\"button\" value=\"우편번호찾기\" onclick=\"postSearch();\">\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"formdiv\">\r\n");
      out.write("            <span class=\"material-symbols-outlined\">home</span>\r\n");
      out.write("            <input type=\"text\" name=\"uaddr1\" id=\"uaddr1\" readonly placeholder=\"주소\"><br>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"formdiv\">\r\n");
      out.write("            <span class=\"material-symbols-outlined\">home</span>\r\n");
      out.write("            <input type=\"text\" name=\"uaddr2\" id=\"uaddr2\" placeholder=\"상세주소를 입력해주세요\"><br>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <!-- <a href=\"javascript:userSubmit();\"><button class=\"btn2\">가입!</button></a> -->\r\n");
      out.write("         <button class=\"insertbtn\" type=\"button\" onclick=\"return userSubmit();\">회원가입</button>\r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("      </form>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("   function sendmail() {\r\n");
      out.write("       let umail = $(\"#umail\").val();\r\n");
      out.write("       console.log(umail);\r\n");
      out.write("\r\n");
      out.write("       $.ajax({\r\n");
      out.write("           url: '/send-email',\r\n");
      out.write("           method: 'POST',\r\n");
      out.write("           data: { to: umail },\r\n");
      out.write("           success: function(result) {\r\n");
      out.write("               console.log(\"서버 응답:\", result);\r\n");
      out.write("               if (result.trim() === \"0\") { \r\n");
      out.write("                   console.log(\"에러\");\r\n");
      out.write("                   alert(\"메일 전송 실패\");\r\n");
      out.write("                   return false;\r\n");
      out.write("               } else {\r\n");
      out.write("                   console.log(\"성공\");\r\n");
      out.write("                   alert(\"메일 전송 성공\");\r\n");
      out.write("                   return false;\r\n");
      out.write("               }\r\n");
      out.write("           },\r\n");
      out.write("           error: function(xhr, status, error) {\r\n");
      out.write("               console.error(\"AJAX 요청 실패:\", status, error);\r\n");
      out.write("               alert(\"AJAX 요청 실패: \" + error);\r\n");
      out.write("           }\r\n");
      out.write("       });\r\n");
      out.write("\r\n");
      out.write("       return false;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   function verifycode(){\r\n");
      out.write("      let umail = $(\"#umail\").val();\r\n");
      out.write("      let inputCode = $(\"input[name='umailChk']\").val();\r\n");
      out.write("      \r\n");
      out.write("      console.log(inputCode);\r\n");
      out.write("      console.log(umail);\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url: '/verify-code',\r\n");
      out.write("         method: 'POST',\r\n");
      out.write("         data:{ to: umail,\r\n");
      out.write("               code: inputCode\r\n");
      out.write("         },\r\n");
      out.write("         success: function(result) {\r\n");
      out.write("            \r\n");
      out.write("               if (result.trim() === \"0\") { \r\n");
      out.write("                   console.log(\"에러\");\r\n");
      out.write("                   alert(\"메일 확인 실패\");\r\n");
      out.write("               } else {\r\n");
      out.write("                   console.log(\"성공\");\r\n");
      out.write("                   alert(\"메일 확인 성공\");\r\n");
      out.write("                   $(\"#mailChk\").val(\"1\");\r\n");
      out.write("                   console.log(mailChk);\r\n");
      out.write("               }\r\n");
      out.write("           },\r\n");
      out.write("           error: function(xhr, status, error) {\r\n");
      out.write("               console.error(\"AJAX 요청 실패:\", status, error);\r\n");
      out.write("               alert(\"AJAX 요청 실패: \" + error);\r\n");
      out.write("           }\r\n");
      out.write("       });\r\n");
      out.write("   }\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("<style>\r\n");
      out.write("    .emailchk{\r\n");
      out.write("       display:none;\r\n");
      out.write("    }\r\n");
      out.write("</style>   \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/user/userform.jsp(160,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty msg}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <script>\r\n");
          out.write("        alert(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\");\r\n");
          out.write("        window.location.href = \"/\"; // alert을 띄운 후 홈으로 이동\r\n");
          out.write("    </script>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
